
AMAZON_ACCESS_KEY_ID: AKIAJBUQH3QUV33FPLSA
AMAZON_SECRET_ACCESS_KEY: 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
GMAIL_SMTP_USER: 
GMAIL_SMTP_PASSWORD: 
HEROKU_USER: sb4f22@gmail.com
HEROKU_PASSWORD: GodisGreat72
